#RAHMAT ARAMADHAN HUSNI(225150607111008)
CREATE DATABASE AKADEMIK;

CREATE TABLE FAKULTAS(
	ID_FAKULTAS SMALLINT NOT NULL,
	FAKULTAS VARCHAR(45) NOT NULL,
	PRIMARY KEY(ID_FAKULTAS)
)
CREATE TABLE JURUSAN(
	ID_JURUSAN SMALLINT NOT NULL,
	ID_FAKULTAS SMALLINT NOT NULL,
	JURUSAN VARCHAR(45),
	PRIMARY KEY (ID_JURUSAN),
	FOREIGN KEY (ID_FAKULTAS) REFERENCES FAKULTAS(ID_FAKULTAS)
)
CREATE TABLE STRATA(
	ID_STRATA SMALLINT NOT NULL,
	SINGKAT VARCHAR(10)NOT NULL,
	STRATA VARCHAR(45)NOT NULL,
	PRIMARY KEY(ID_STRATA)
)
CREATE TABLE PROGRAM_STUDI(
	ID_PROGRAM_STUDI SMALLINT NOT NULL,
	ID_STRATA SMALLINT NOT NULL,
	ID_JURUSAN SMALLINT NOT NULL,
	PROGRAM_STUDI VARCHAR(60) NOT NULL,
	PRIMARY KEY(ID_PROGRAM_STUDI),
	FOREIGN KEY(ID_STRATA) 
	REFERENCES STRATA(ID_STRATA),
	FOREIGN KEY(ID_JURUSAN)
	REFERENCES JURUSAN(ID_JURUSAN)
)
CREATE TABLE SELEKSI_MASUK(
	ID_SELEKSI_MASUK SMALLINT NOT NULL,
	SINGKAT VARCHAR(12) NOT NULL,
	SELEKSI_MASUK VARCHAR(45),
	PRIMARY KEY(ID_SELEKSI_MASUK)
) 
CREATE TABLE MAHASISWA(
	NIM VARCHAR(45) NOT NULL,
	ID_SELEKSI_MASUK SMALLINT NOT NULL,
	ID_PROGRAM_STUDI SMALLINT NOT NULL,
	NAMA VARCHAR(45),
	ANGKATAN SMALLINT,
	TGL_LAHIR DATE,
	KOTA_LAHIR VARCHAR(60),
	JENIS_KELAMIN CHAR(1)
	CHECK (JENIS_KELAMIN IN ('P','L')),
	PRIMARY KEY(NIM),
	FOREIGN KEY(ID_SELEKSI_MASUK) 
	REFERENCES SELEKSI_MASUK(ID_SELEKSI_MASUK),
	FOREIGN KEY(ID_PROGRAM_STUDI)
	REFERENCES PROGRAM_STUDI(ID_PROGRAM_STUDI)
)

INSERT INTO fakultas 
VALUES (1,'Ekonomi & Bisnis'),(2,'Ilmu Komputer');

INSERT INTO jurusan 
VALUES (21,2,'Informatika'),(22,2,'Sistem Informasi'),(23, 2, 'Teknik Komputer')

INSERT INTO strata 
VALUES (1,'D1','Diploma'),(2,'S1','Sarjana'),(3,'S2','Magister')

INSERT INTO program_studi 
VALUES (211,2,21,'Teknik Informatika'),(212,2,21,'Teknik Komputer'),(219,3,21,'Magiste Ilmu Komputer')

INSERT INTO seleksi_masuk 
VALUES (1,'SNMPTN','SELEKSI NASIONAL MAHASISWA PERGURUAN TINGGI NEGERI'),(2,'SBMPTN','SELEKSI BERSAMA MAHASISWA PERGURUAN TINGGI NEGERI')

INSERT INTO mahasiswa 
VALUES ('155150400',1,211,'JONI',2015,'1997-01-01','Malang','P'),('155150401',2,212,'JONO',2015,'1997-10-01','Situbondo','L')

UPDATE mahasiswa 
SET KOTA_LAHIR='MOJOKERTO'
WHERE NIM='155150400'

DELETE FROM mahasiswa
WHERE NIM='155150400';

SELECT * FROM akademik.fakultas;

#RAHMAT ARAMADHAN HUSNI(225150607111008)